# Comprehensive Backup Strategy for Dating Profile Optimizer
# Production-grade backup and disaster recovery configuration

backup_strategy:
  # Database backup configuration
  database:
    postgresql:
      # Primary backup method - pg_dump with compression
      method: "pg_dump"
      format: "custom"  # Custom format for flexibility and compression
      compression: 9
      
      # Backup frequency
      full_backup:
        schedule: "0 2 * * *"  # Daily at 2 AM
        retention: "30 days"
        
      incremental_backup:
        schedule: "0 */6 * * *"  # Every 6 hours
        retention: "7 days"
        method: "wal_shipping"
        
      # Point-in-time recovery
      point_in_time_recovery:
        enabled: true
        wal_archive_timeout: "5min"
        max_wal_senders: 3
        wal_keep_segments: 64
        
      # Backup destinations
      destinations:
        primary: "s3://dating-optimizer-backups/database/"
        secondary: "gs://dating-optimizer-backups-dr/database/"
        local: "/opt/backups/database/"
        
      # Encryption
      encryption:
        enabled: true
        method: "AES-256"
        key_management: "aws_kms"  # or "vault", "local_key"
        
      # Verification
      verification:
        enabled: true
        test_restore_frequency: "weekly"
        integrity_check: true

  # Application data backup
  application_data:
    # User uploaded photos (if stored locally)
    user_uploads:
      source: "/app/uploads/"
      schedule: "0 3 * * *"  # Daily at 3 AM
      retention: "90 days"
      destinations:
        - "s3://dating-optimizer-backups/uploads/"
        - "gs://dating-optimizer-backups-dr/uploads/"
      sync_method: "rsync"
      compression: true
      
    # Application logs
    logs:
      source: "/app/logs/"
      schedule: "0 4 * * *"  # Daily at 4 AM
      retention: "30 days"
      destinations:
        - "s3://dating-optimizer-backups/logs/"
      compression: true
      
    # Configuration files
    config:
      source: "/app/config/"
      schedule: "0 */12 * * *"  # Twice daily
      retention: "60 days"
      destinations:
        - "s3://dating-optimizer-backups/config/"
        - "gs://dating-optimizer-backups-dr/config/"

  # Redis data backup
  redis:
    # RDB snapshots
    rdb_backup:
      schedule: "0 1 * * *"  # Daily at 1 AM
      retention: "14 days"
      compression: true
      
    # AOF backup for point-in-time recovery
    aof_backup:
      enabled: true
      schedule: "0 */4 * * *"  # Every 4 hours
      retention: "7 days"
      
    destinations:
      - "s3://dating-optimizer-backups/redis/"
      - "gs://dating-optimizer-backups-dr/redis/"

  # System configuration backup
  system:
    # Docker configurations
    docker_configs:
      source: "/opt/dating-optimizer/"
      schedule: "0 5 * * *"  # Daily at 5 AM
      retention: "60 days"
      
    # SSL certificates
    ssl_certificates:
      source: "/etc/letsencrypt/"
      schedule: "0 6 * * *"  # Daily at 6 AM
      retention: "90 days"
      
    # Monitoring configuration
    monitoring:
      source: "/opt/monitoring/"
      schedule: "0 7 * * *"  # Daily at 7 AM
      retention: "60 days"

# Disaster Recovery Configuration
disaster_recovery:
  # Recovery Time Objective (RTO) and Recovery Point Objective (RPO)
  objectives:
    rto: "4 hours"      # Maximum acceptable downtime
    rpo: "15 minutes"   # Maximum acceptable data loss
    
  # Multi-region setup
  regions:
    primary: "us-east-1"
    secondary: "us-west-2"
    tertiary: "eu-west-1"
    
  # Automated failover
  automated_failover:
    enabled: true
    health_check_interval: "30s"
    failure_threshold: 3
    recovery_threshold: 2
    
  # Database replication
  database_replication:
    method: "streaming_replication"
    synchronous: false  # Async for performance
    standby_servers:
      - region: "us-west-2"
        priority: 1
      - region: "eu-west-1"
        priority: 2
        
  # Application redundancy
  application_redundancy:
    active_regions: 2
    passive_regions: 1
    load_balancing: "geographic"
    
  # Data synchronization
  data_sync:
    file_storage: "cloudinary"  # Already handles replication
    cache_replication: true
    config_sync: true

# Backup automation scripts
automation:
  # Main backup orchestrator
  backup_orchestrator:
    image: "dating-optimizer/backup-orchestrator:latest"
    schedule: "0 1 * * *"  # Daily at 1 AM
    timeout: "4 hours"
    
  # Individual backup jobs
  jobs:
    database_full:
      script: "/backup-scripts/db-full-backup.sh"
      resources:
        memory: "1Gi"
        cpu: "0.5"
        
    database_incremental:
      script: "/backup-scripts/db-incremental-backup.sh"
      resources:
        memory: "512Mi"
        cpu: "0.25"
        
    file_backup:
      script: "/backup-scripts/file-backup.sh"
      resources:
        memory: "512Mi"
        cpu: "0.25"
        
    verification:
      script: "/backup-scripts/verify-backups.sh"
      schedule: "0 8 * * 1"  # Weekly on Monday
      resources:
        memory: "2Gi"
        cpu: "1.0"

# Monitoring and alerting for backups
monitoring:
  metrics:
    - backup_success_rate
    - backup_duration
    - backup_size
    - restore_test_success
    - rpo_compliance
    - rto_compliance
    
  alerts:
    backup_failure:
      threshold: "1 failure"
      severity: "critical"
      notification: "immediate"
      
    backup_duration_high:
      threshold: "2 hours"
      severity: "warning"
      notification: "delayed"
      
    restore_test_failure:
      threshold: "1 failure"
      severity: "critical"
      notification: "immediate"
      
    rpo_violation:
      threshold: "30 minutes"
      severity: "critical"
      notification: "immediate"

# Compliance and audit
compliance:
  # Data retention policies
  retention_policies:
    user_data: "7 years"  # Regulatory requirement
    financial_data: "10 years"
    logs: "2 years"
    backups: "1 year"
    
  # Audit requirements
  audit:
    backup_logs: true
    restore_logs: true
    access_logs: true
    integrity_verification: true
    
  # Encryption requirements
  encryption:
    in_transit: true
    at_rest: true
    key_rotation: "quarterly"
    
  # Geographic restrictions
  data_sovereignty:
    eu_data_in_eu: true
    us_data_in_us: true
    cross_border_restrictions: true

# Testing and validation
testing:
  # Regular restore tests
  restore_tests:
    frequency: "weekly"
    test_types:
      - full_restore
      - point_in_time_restore
      - partial_restore
      - cross_region_restore
      
  # Disaster recovery drills
  dr_drills:
    frequency: "quarterly"
    scenarios:
      - primary_region_failure
      - database_corruption
      - complete_infrastructure_loss
      - cyber_attack_recovery
      
  # Backup validation
  validation:
    checksum_verification: true
    restoration_testing: true
    data_integrity_checks: true
    performance_benchmarks: true

# Cost optimization
cost_optimization:
  # Storage tiering
  storage_classes:
    recent_backups: "STANDARD"  # Last 30 days
    archive_backups: "GLACIER"  # 30-365 days
    long_term_archive: "DEEP_ARCHIVE"  # > 1 year
    
  # Compression and deduplication
  optimization:
    compression: true
    deduplication: true
    incremental_forever: true
    
  # Lifecycle policies
  lifecycle:
    transition_to_ia: "30 days"
    transition_to_glacier: "90 days"
    transition_to_deep_archive: "365 days"
    delete_after: "2555 days"  # 7 years