# Security Hardening Configuration for Dating Profile Optimizer
# Comprehensive security measures for production environment

security_hardening:
  # Network security
  network:
    firewall:
      enabled: true
      default_policy: "DENY"
      rules:
        # Allow HTTP/HTTPS traffic
        - port: 80
          protocol: "tcp"
          source: "0.0.0.0/0"
          action: "ALLOW"
        - port: 443
          protocol: "tcp"
          source: "0.0.0.0/0"
          action: "ALLOW"
        
        # SSH access (restricted)
        - port: 22
          protocol: "tcp"
          source: "10.0.0.0/8"  # VPN network only
          action: "ALLOW"
        
        # Database access (internal only)
        - port: 5432
          protocol: "tcp"
          source: "172.20.0.0/16"  # Docker network
          action: "ALLOW"
        
        # Redis access (internal only)
        - port: 6379
          protocol: "tcp"
          source: "172.20.0.0/16"
          action: "ALLOW"
        
        # Monitoring ports (restricted)
        - port: 9090
          protocol: "tcp"
          source: "10.0.0.0/8"
          action: "ALLOW"
        - port: 3000
          protocol: "tcp"
          source: "10.0.0.0/8"
          action: "ALLOW"
      
      # DDoS protection
      rate_limiting:
        enabled: true
        requests_per_minute: 100
        burst_size: 50
        ban_duration: "10m"
      
      # Intrusion detection
      ids:
        enabled: true
        engine: "suricata"
        rules: "emerging-threats"
        log_alerts: true
    
    # VPN configuration
    vpn:
      type: "wireguard"
      enabled: true
      network: "10.0.0.0/24"
      dns_servers:
        - "1.1.1.1"
        - "1.0.0.1"
      allowed_clients: 20
      
    # Network segmentation
    segmentation:
      # DMZ for public-facing services
      dmz:
        subnet: "172.20.1.0/24"
        services:
          - nginx
          - api (limited exposure)
      
      # Internal network for databases and cache
      internal:
        subnet: "172.20.2.0/24"
        services:
          - postgresql
          - redis
          - monitoring
      
      # Management network
      management:
        subnet: "172.20.3.0/24"
        services:
          - ssh
          - monitoring-admin
          - backup-services

  # Container security
  container_security:
    # Docker security settings
    docker:
      # Use non-root user
      run_as_non_root: true
      user_id: 1001
      group_id: 1001
      
      # Security options
      security_opts:
        - "no-new-privileges:true"
        - "seccomp:unconfined"
      
      # Resource limits
      resource_limits:
        memory: "1g"
        cpu: "1.0"
        pids: 100
        
      # Read-only filesystem
      read_only_root_filesystem: true
      tmpfs_mounts:
        - "/tmp:rw,noexec,nosuid,size=100m"
        - "/var/tmp:rw,noexec,nosuid,size=50m"
      
      # Capabilities (drop all, add only necessary)
      cap_drop:
        - "ALL"
      cap_add:
        - "NET_BIND_SERVICE"  # For binding to port 80/443
    
    # Image security
    image_security:
      # Base image requirements
      base_image:
        approved_images:
          - "node:18-alpine"
          - "postgres:15-alpine"
          - "redis:7-alpine"
          - "nginx:1.25-alpine"
        
      # Vulnerability scanning
      vulnerability_scanning:
        enabled: true
        scanner: "trivy"
        scan_schedule: "daily"
        fail_on_critical: true
        fail_on_high: true
        
      # Image signing
      image_signing:
        enabled: true
        cosign: true
        verify_signatures: true
        
      # Registry security
      registry:
        use_https: true
        require_auth: true
        scan_images: true
        
    # Runtime security
    runtime_security:
      # AppArmor/SELinux profiles
      mandatory_access_control:
        type: "apparmor"
        profiles:
          dating-api: "/etc/apparmor.d/dating-api"
          nginx: "/etc/apparmor.d/nginx"
          
      # Seccomp profiles
      seccomp:
        enabled: true
        default_profile: "/etc/seccomp/default.json"
        custom_profiles:
          api: "/etc/seccomp/api.json"
          
      # Runtime monitoring
      runtime_monitoring:
        enabled: true
        tool: "falco"
        rules: "/etc/falco/dating-optimizer-rules.yaml"

  # Application security
  application:
    # Authentication and authorization
    auth:
      # JWT configuration
      jwt:
        algorithm: "RS256"
        expiry: "15m"
        refresh_expiry: "7d"
        issuer: "api.datingoptimizer.com"
        
      # Password policy
      password_policy:
        min_length: 12
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_symbols: true
        history: 5
        max_age: "90d"
        
      # Multi-factor authentication
      mfa:
        enabled: true
        methods:
          - "totp"
          - "sms"
        backup_codes: true
        
      # Session management
      sessions:
        secure_cookies: true
        http_only: true
        same_site: "strict"
        max_age: "2h"
        
    # Input validation and sanitization
    input_security:
      # Request size limits
      request_limits:
        max_body_size: "10mb"
        max_file_size: "50mb"
        max_files: 10
        
      # Content type validation
      content_types:
        allowed_types:
          - "application/json"
          - "multipart/form-data"
          - "application/x-www-form-urlencoded"
          - "image/jpeg"
          - "image/png"
          - "image/webp"
        
      # SQL injection prevention
      sql_injection:
        use_prepared_statements: true
        parameterized_queries: true
        orm_validation: true
        
      # XSS prevention
      xss_protection:
        content_security_policy: true
        output_encoding: true
        input_sanitization: true
        
    # API security
    api_security:
      # Rate limiting
      rate_limiting:
        enabled: true
        requests_per_minute: 60
        burst_size: 20
        
        # Endpoint-specific limits
        endpoints:
          "/api/auth/login":
            requests_per_minute: 5
            burst_size: 2
          "/api/photos/analyze":
            requests_per_minute: 10
            burst_size: 3
          "/api/bio/generate":
            requests_per_minute: 5
            burst_size: 1
            
      # CORS configuration
      cors:
        enabled: true
        allowed_origins:
          - "https://app.datingoptimizer.com"
          - "https://admin.datingoptimizer.com"
        allowed_methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        allowed_headers:
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
        credentials: true
        max_age: 86400
        
      # API versioning
      versioning:
        strategy: "header"
        header_name: "API-Version"
        default_version: "v1"
        supported_versions:
          - "v1"
        
      # Request/Response logging
      logging:
        enabled: true
        log_requests: true
        log_responses: false  # Sensitive data
        sanitize_data: true

  # Data security
  data_security:
    # Encryption at rest
    encryption_at_rest:
      database:
        enabled: true
        algorithm: "AES-256"
        key_management: "aws_kms"
        key_rotation: "quarterly"
        
      file_storage:
        enabled: true
        algorithm: "AES-256-GCM"
        
      backups:
        enabled: true
        algorithm: "AES-256"
        
    # Encryption in transit
    encryption_in_transit:
      tls_version: "1.3"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
        - "TLS_AES_128_GCM_SHA256"
      
      # Certificate pinning
      certificate_pinning:
        enabled: false  # Use Certificate Transparency instead
        
      # HSTS
      hsts:
        enabled: true
        max_age: 31536000
        include_subdomains: true
        preload: true
        
    # Data loss prevention
    dlp:
      enabled: true
      patterns:
        - credit_cards
        - ssn
        - email_addresses
        - phone_numbers
      actions:
        - alert
        - block
        - audit
        
    # Data retention
    retention:
      user_data: "7 years"
      logs: "2 years"
      analytics: "3 years"
      backups: "1 year"
      
    # Data anonymization
    anonymization:
      enabled: true
      methods:
        - pseudonymization
        - data_masking
        - generalization
      schedule: "monthly"

  # Infrastructure security
  infrastructure:
    # Operating system hardening
    os_hardening:
      # User management
      users:
        disable_root_login: true
        password_aging: true
        account_lockout: true
        
      # File system security
      filesystem:
        mount_options:
          - "nodev"
          - "nosuid"
          - "noexec"
        permissions:
          strict_permissions: true
          umask: "027"
          
      # Kernel security
      kernel:
        disable_unused_modules: true
        enable_kaslr: true
        enable_smep: true
        enable_smap: true
        
    # Service hardening
    services:
      # SSH hardening
      ssh:
        protocol_version: 2
        permit_root_login: false
        password_authentication: false
        key_based_auth: true
        max_auth_tries: 3
        client_alive_interval: 300
        
      # Database hardening
      postgresql:
        ssl_only: true
        log_connections: true
        log_disconnections: true
        log_statement: "all"
        shared_preload_libraries:
          - "pg_stat_statements"
          - "auto_explain"
          
      # Web server hardening
      nginx:
        server_tokens: false
        hide_version: true
        security_headers: true
        
    # Patch management
    patch_management:
      automatic_updates: true
      security_updates: "immediate"
      regular_updates: "weekly"
      testing_environment: true
      rollback_plan: true

  # Monitoring and incident response
  security_monitoring:
    # SIEM integration
    siem:
      enabled: true
      system: "elasticsearch"
      log_sources:
        - application_logs
        - system_logs
        - security_logs
        - network_logs
        
    # Intrusion detection
    ids:
      enabled: true
      network_ids: true
      host_ids: true
      signatures: "snort"
      
    # Vulnerability management
    vulnerability_management:
      scanner: "openvas"
      scan_frequency: "weekly"
      auto_remediation: false
      
    # Incident response
    incident_response:
      playbooks:
        - security_breach
        - data_breach
        - ddos_attack
        - malware_detection
      notification_channels:
        - slack
        - email
        - sms
        - pagerduty
        
    # Threat intelligence
    threat_intelligence:
      enabled: true
      sources:
        - "misp"
        - "opencti"
      indicators:
        - ip_addresses
        - domains
        - file_hashes
        - yara_rules

  # Compliance and audit
  compliance:
    frameworks:
      - "SOC2"
      - "ISO27001"
      - "GDPR"
      - "CCPA"
      
    audit_logging:
      enabled: true
      events:
        - authentication
        - authorization
        - data_access
        - configuration_changes
        - administrative_actions
      retention: "7 years"
      integrity_protection: true
      
    regular_assessments:
      penetration_testing: "quarterly"
      vulnerability_assessment: "monthly"
      security_review: "weekly"
      compliance_audit: "annually"
      
    reporting:
      executive_summary: "monthly"
      technical_report: "weekly"
      incident_reports: "immediate"
      compliance_reports: "quarterly"

  # Backup security
  backup_security:
    encryption: true
    access_control: true
    integrity_verification: true
    offsite_storage: true
    test_restoration: "monthly"
    
  # Disaster recovery security
  dr_security:
    secure_communication: true
    identity_verification: true
    access_logging: true
    change_management: true